parent_dependent_type_dict = {
    ("cmd_sqrt",  ("symb", "[")):  "opn_degr",
    ("opn_degr",  ("symb", "]")):  "cls_degr",

    ("cmd_sbstk", ("symb", "{")):  "opn_sbstk",
    ("cmd_sbstk", ("symb", "}")):  "cls_sbstk",

    ("cmd_text",  ("symb", "{")):  "opn_text",
    ("opn_text",  ("symb", "}")):  "cls_text",
    ("opn_text",  ("symb", " ")):  "txt_leaf",

    ("opn_dllr",  ("symb", "$")):  "cls_dllr",
    ("opn_ddlr",  ("symb", "$$")): "cls_ddlr",

    ("cmd_bgin",  ("cmnd", "\\")): "row_sep",
    ("cmd_bgin",  ("cmnd", "newline")): "row_sep",
    ("opn_root",  ("cmnd", "\\")): "row_sep",
    ("opn_root",  ("cmnd", "newline")): "row_sep",
    ("opn_brak",  ("cmnd", "\\")): "row_sep",
    ("opn_brak",  ("cmnd", "newline")): "row_sep",
    ("opn_pren",  ("cmnd", "\\")): "row_sep",
    ("opn_pren",  ("cmnd", "newline")): "row_sep",
    ("opn_dllr",  ("cmnd", "\\")): "row_sep",
    ("opn_dllr",  ("cmnd", "newline")): "row_sep",
    ("opn_ddlr",  ("cmnd", "\\")): "row_sep",
    ("opn_ddlr",  ("cmnd", "newline")): "row_sep",
    ("cmd_sbstk", ("cmnd", "\\")): "row_sep",
    ("cmd_sbstk", ("cmnd", "newline")): "row_sep",
}

type_dependent_type_dict = {}

type_dict = {
    ("meta",     "start"): "opn_root", ("meta",     "end"): "cls_root",
    ("symb",         "^"): "sup_scrpt", ("symb",      "_"): "sub_scrpt",
    ("symb", "$"): "opn_dllr",  ("symb",  "$$"): "opn_ddlr",
    ("symb", "&"): "amp_sep",
    ("cmnd", "["): "opn_brak",  ("cmnd",  "]"): "cls_brak",
    ("cmnd", "("): "opn_pren",  ("cmnd",  ")"): "cls_pren",
    ("symb", "{"): "opn_brac",  ("symb",  "}"): "cls_brac",
    ("symb", " "): "txt_invs",

    ("cmnd",  "left"): "opn_dlim", ("cmnd", "right"): "cls_dlim",
    ("cmnd",  "bigl"): "big_dlim", ("cmnd",   "big"): "big_dlim",
    ("cmnd",  "bigr"): "big_dlim", ("cmnd",  "Bigl"): "big_dlim",
    ("cmnd",   "Big"): "big_dlim", ("cmnd",  "Bigr"): "big_dlim",
    ("cmnd", "biggl"): "big_dlim", ("cmnd",  "bigg"): "big_dlim",
    ("cmnd", "biggr"): "big_dlim", ("cmnd", "Biggl"): "big_dlim",
    ("cmnd",  "Bigg"): "big_dlim", ("cmnd", "Biggr"): "big_dlim",

    ("cmnd",  "sqrt"): "cmd_sqrt",

    ("cmnd",  "frac"): "cmd_frac", ("cmnd", "tfrac"): "cmd_frac",
    ("cmnd", "dfrac"): "cmd_frac", ("cmnd", "cfrac"): "cmd_frac",

    ("cmnd",   "sum"): "ctr_base", ("cmnd", "prod"): "ctr_base",
    ("cmnd",   "lim"): "ctr_base",
    ("cmnd", "argmax"): "ctr_base", ("cmnd", "argmin"): "ctr_base",
    ("cmnd", "injlim"): "ctr_base", ("cmnd", "projlim"): "ctr_base",
    ("cmnd", "varinjlim"): "ctr_base", ("cmnd", "varprojlim"): "ctr_base",
    ("cmnd", "varliminf"): "ctr_base", ("cmnd", "varlimsup"): "ctr_base",
    ("cmnd",    "plim"): "ctr_base",
    ("cmnd", "liminf"): "ctr_base", ("cmnd", "limsup"): "ctr_base",
    ("cmnd",    "det"): "ctr_base", ("cmnd",     "Pr"): "ctr_base",
    ("cmnd",    "gcd"): "ctr_base",
    ("cmnd",    "inf"): "ctr_base", ("cmnd",    "max"): "ctr_base",
    ("cmnd",    "min"): "ctr_base", ("cmnd",    "sup"): "ctr_base",

    ("cmnd", "binom"): "cmd_binom", ("cmnd", "dbinom"): "cmd_binom",

    ("cmnd",  "limits"): "cmd_lmts", ("cmnd",     "acute"): "cmd_acnt",
    ("cmnd",     "bar"): "cmd_acnt", ("cmnd",     "breve"): "cmd_acnt",
    ("cmnd",   "check"): "cmd_acnt", ("cmnd",      "ddot"): "cmd_acnt",
    ("cmnd",     "dot"): "cmd_acnt", ("cmnd",     "grave"): "cmd_acnt",
    ("cmnd",     "hat"): "cmd_acnt", ("cmnd",  "mathring"): "cmd_acnt",
    ("cmnd",   "tilde"): "cmd_acnt", ("cmnd",       "vec"): "cmd_acnt",
    ("cmnd", "widehat"): "cmd_acnt", ("cmnd", "widetilde"): "cmd_acnt",

    ("cmnd",  "mathrm"): "cmd_font", ("cmnd",     "mathbf"): "cmd_font",
    ("cmnd",  "mathsf"): "cmd_font", ("cmnd",     "mathtt"): "cmd_font",
    ("cmnd",  "mathit"): "cmd_font", ("cmnd", "mathnormal"): "cmd_font",
    ("cmnd", "mathcal"): "cmd_font", ("cmnd",   "mathfrak"): "cmd_font",
    ("cmnd",  "mathbb"): "cmd_font", ("cmnd",    "mathscr"): "cmd_font",

    ("cmnd", "operatorname"): "cmd_font",  # issue #7

    ("cmnd", "text"): "cmd_text",

    ("cmnd", "substack"): "cmd_sbstk",
    ("cmnd",    "\\"): "row_sep", ("cmnd", "newline"): "row_sep",
    ("cmnd", "textstyle"): "cmd_styl",
    ("cmnd", "displaystyle"): "cmd_styl",
    ("cmnd", "scriptstyle"): "cmd_styl",
    ("cmnd", "scriptscriptstyle"): "cmd_styl",
}

self_dependent_type_dict = {
    "symb": "txt_leaf",
    "alph": "txt_leaf",
    "numb": "txt_leaf",
    "cmnd": "cmd_leaf",
    "env_bgin": "cmd_bgin",
    "env_end": "cmd_end",
}

# node_info( ("only/only_not", popable_by["node_type"])
#            (add_amount)
#            (can_add_to_nodes_tree, "err if/if_not", under[])
#            (can_be_children, can_break_parent)
#            (token_depented_render, rendering_function)
type_info_dict = {
    "opn_root":  ((True, ["cls_root",]),
                  (1,),
                  (True, True, []),
                  (False, False),
                  (False, "render_root")),
    "opn_brac":  ((True, ["cls_brac",]),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_concat")),
    "opn_degr":  ((True, ["cls_degr",]),
                  (1,),
                  (True, False, ["cmd_sqrt",]),
                  (True, False),
                  (False, "render_concat")),
    "opn_dlim":  ((True, ["cls_dlim",]),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_open_delimiter")),
    "cmd_sqrt":  ((False, ["opn_degr",]),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_square_root")),
    "cmd_frac":  ((False, []),
                  (2,),
                  (True, True, []),
                  (True, False),
                  (False, "render_fraction")),
    "cmd_binom": ((False, []),
                  (2,),
                  (True, True, []),
                  (True, False),
                  (False, "render_binomial")),
    "big_dlim":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (True, "render_big_delimiter")),
    "sup_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_sup_script")),
    "sub_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_sub_script")),
    "top_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_top_script")),
    "btm_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_bottom_script")),
    "cls_dlim":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_close_delimiter")),
    "cmd_acnt":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (True, "render_accents")),
    "cmd_font":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (True, "render_font")),
    "cmd_lmts":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False),
                  (False, )),
    "ctr_base":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False),
                  (True, "render_leaf")),
    "txt_leaf":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False),
                  (True, "render_leaf")),
    "txt_info":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False),
                  (True, "render_text_info")),
    "txt_invs":  ((True, []),
                  (0,),
                  (False, True, []),
                  (False, False),
                  (False, )),
    "cmd_leaf":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False),
                  (True, "render_leaf")),
    "cmd_styl":  ((True, []),
                  (0,),
                  (False, True, []),
                  (False, False),
                  (False, )),
    "cls_root":  ((True, []),
                  (0,),
                  (False, False, ["opn_root",]),
                  (False, False),
                  (False, )),
    "cls_brac":  ((True, []),
                  (0,),
                  (False, False, ["opn_brac",]),
                  (False, False),
                  (False, )),
    "cls_degr":  ((True, []),
                  (0,),
                  (False, False, ["opn_degr",]),
                  (False, False),
                  (False, )),
    "cls_brak":  ((True, []),
                  (0,),
                  (False, False, ["opn_brak",]),
                  (False, False),
                  (False, )),
    "cls_pren":  ((True, []),
                  (0,),
                  (False, False, ["opn_pren",]),
                  (False, False),
                  (False, )),
    "cls_dllr":  ((True, []),
                  (0,),
                  (False, False, ["opn_dllr",]),
                  (False, False),
                  (False, )),
    "cls_ddlr":  ((True, []),
                  (0,),
                  (False, False, ["opn_ddlr",]),
                  (False, True),
                  (False, )),
    "cmd_end":   ((False, []),
                  (0,),
                  (True, False, ["cmd_bgin",]),
                  (False, True),
                  (True, "render_end")),
    "cls_text":  ((True, []),
                  (0,),
                  (False, False, ["opn_text",]),
                  (False, False),
                  (False, )),
    "opn_brak":  ((True, ["cls_brak",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False),
                  (False, "render_lines")),
    "opn_pren":  ((True, ["cls_pren",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False),
                  (False, "render_lines")),
    "opn_dllr":  ((True, ["cls_dllr",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False),
                  (False, "render_lines")),
    "opn_ddlr":  ((True, ["cls_ddlr",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False),
                  (False, "render_lines")),
    "cmd_bgin":  ((True, ["cmd_end",]),
                  (1,),
                  (True, False, ["opn_root", "opn_dlim", "opn_brac"]),
                  (True, False),
                  (True, "render_begin")),
    "opn_text":  ((True, ["cls_text",]),
                  (1,),
                  (True, False, ["cmd_text",]),
                  (True, False),
                  (False, "render_concat")),
    "cmd_text":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (True, "render_font")),
    "cmd_sbstk": ((True, ["cls_sbstk",]),
                  (1,),
                  (True, True, []),
                  (True, False),
                  (False, "render_substack")),
    "opn_sbstk": ((True, []),
                  (0,),
                  (False, True, []),
                  (False, False),
                  (False, )),
    "cls_sbstk": ((True, []),
                  (0,),
                  (False, True, []),
                  (False, False),
                  (False, )),
    "row_sep":   ((True, []),
                  (0,),
                  (True, False, ["opn_root", "opn_brak", "opn_pren",
                                 "opn_dllr", "opn_ddlr", "cmd_bgin",
                                 "cmd_sbstk"]),
                  (True, False),
                  (False, "render_empty")),
    "amp_sep":   ((True, []),
                  (0,),
                  (True, False, ["cmd_bgin"]),
                  (True, False),
                  (False, "render_empty")),
}
