# One-to-one LaTeX command -> Unicode symbol mappings.
# Generated from katex-supported.md (KaTeX supported functions).
# Sections follow the checklist order; unknown glyphs are left as [].
symbols = {
    # 1. Delimiters
    "lparen": ['('],
    "rparen": [')'],
    "lceil": ['⌈'],
    "rceil": ['⌉'],
    "uparrow": ['↑'],
    "lbrack": ['['],
    "rbrack": [']'],
    "lfloor": ['⌊'],
    "rfloor": ['⌋'],
    "downarrow": ['↓'],
    "{": ['{'],
    "}": ['}'],
    "lbrace": ['{'],
    "rbrace": ['}'],
    "lmoustache": ['⎰'],
    "rmoustache": ['⎱'],
    "updownarrow": ['↕'],
    "langle": ['⟨'],
    "rangle": ['⟩'],
    "lgroup": ['⟮'],
    "rgroup": ['⟯'],
    "Uparrow": ['⇑'],
    "vert": ['∣'],
    "ulcorner": ['⌜'],
    "urcorner": ['⌝'],
    "Downarrow": ['⇓'],
    "|": ['∥'],
    "Vert": ['∥'],
    "llcorner": ['⌞'],
    "lrcorner": ['⌟'],
    "Updownarrow": ['⇕'],
    "lvert": ['|'],
    "rvert": ['|'],
    "lVert": ['∥'],
    "rVert": ['∥'],
    "backslash": ['\\'],
    "lang": ['⟨'],
    "rang": ['⟩'],
    "lt": ['⟨'],
    "gt": ['⟩'],
    "llbracket": ['⟦'],
    "rrbracket": ['⟧'],
    "lBrace": ['⦃'],
    "rBrace": ['⦄'],

    # 2. Greek Letters
    "Alpha": ['A'],
    "Beta": ['B'],
    "Gamma": ['Γ'],
    "Delta": ['Δ'],
    "Epsilon": ['E'],
    "Zeta": ['Z'],
    "Eta": ['H'],
    "Theta": ['Θ'],
    "Iota": ['I'],
    "Kappa": ['K'],
    "Lambda": ['Λ'],
    "Mu": ['M'],
    "Nu": ['N'],
    "Xi": ['Ξ'],
    "Omicron": ['O'],
    "Pi": ['Π'],
    "Rho": ['P'],
    "Sigma": ['Σ'],
    "Tau": ['T'],
    "Upsilon": ['Υ'],
    "Phi": ['Φ'],
    "Chi": ['X'],
    "Psi": ['Ψ'],
    "Omega": ['Ω'],
    "varGamma": ['𝛤'],
    "varDelta": ['𝛥'],
    "varTheta": ['𝛩'],
    "varLambda": ['𝛬'],
    "varXi": ['𝛯'],
    "varPi": ['𝛱'],
    "varSigma": ['𝛴'],
    "varUpsilon": ['𝛶'],
    "varPhi": ['𝛷'],
    "varPsi": ['𝛹'],
    "varOmega": ['𝛺'],
    "alpha": ['α'],
    "beta": ['β'],
    "gamma": ['γ'],
    "delta": ['δ'],
    "epsilon": ['ϵ'],
    "zeta": ['ζ'],
    "eta": ['η'],
    "theta": ['θ'],
    "iota": ['ι'],
    "kappa": ['κ'],
    "lambda": ['λ'],
    "mu": ['μ'],
    "nu": ['ν'],
    "xi": ['ξ'],
    "omicron": ['ο'],
    "pi": ['π'],
    "rho": ['ρ'],
    "sigma": ['σ'],
    "tau": ['τ'],
    "upsilon": ['υ'],
    "phi": ['ϕ'],
    "chi": ['χ'],
    "psi": ['ψ'],
    "omega": ['ω'],
    "varepsilon": ['𝜀'],
    "varkappa": ['𝜘'],
    "vartheta": ['𝜗'],
    "thetasym": ['𝜗'],
    "varpi": ['𝜛'],
    "varrho": ['𝜚'],
    "varsigma": ['𝜍'],
    "varphi": ['𝜑'],
    "digamma": ['ϝ'],

    # 3. Other Letters
    "imath": ['ı'],
    "nabla": ['∇'],
    "Im": ['ℑ'],
    "Reals": ['ℝ'],
    "OE": ['Œ'],  # \text-wrapped
    "jmath": ['ȷ'],
    "partial": ['∂'],
    "image": ['ℑ'],
    "wp": ['℘'],
    "o": ['ø'],  # \text-wrapped
    "aleph": ['ℵ'],
    "Game": ['⅁'],
    "Bbbk": ['𝕜'],
    "weierp": ['℘'],
    "O": ['Ø'],  # \text-wrapped
    "alef": ['ℵ'],
    "Finv": ['Ⅎ'],
    "N": ['ℕ'],
    "Z": ['ℤ'],
    "ss": ['ß'],  # \text-wrapped
    "alefsym": ['ℵ'],
    "cnums": ['ℂ'],
    "natnums": ['ℕ'],
    "aa": ['å'],  # \text-wrapped
    "i": ['ı'],  # \text-wrapped
    "beth": ['ℶ'],
    "Complex": ['ℂ'],
    "R": ['ℝ'],
    "AA": ['Å'],  # \text-wrapped
    "j": ['ȷ'],  # \text-wrapped, fill in
    "gimel": ['ℷ'],
    "ell": ['ℓ'],
    "Re": ['ℜ'],
    "ae": ['æ'],  # \text-wrapped
    "daleth": ['ℸ'],
    "hbar": ['ℏ'],
    "real": ['ℜ'],
    "AE": ['Æ'],  # \text-wrapped
    "eth": ['ð'],
    "hslash": ['ℏ'],
    "reals": ['ℝ'],
    "oe": ['œ'],  # \text-wrapped, fill in

    # 4. Spacing
    ",": [' '],
    "thinspace": [' '],
    ">": [' '],
    ":": [' '],
    "medspace": [' '],
    ";": [' '],
    "thickspace": [' '],
    "enspace": [' '],
    "quad": [' ', ' '],
    "qquad": [' ', ' ', ' ', ' '],
    "~": [' '],
    " ": [' '],
    "nobreakspace": [' '],
    "space": [' '],
    # "vphantom": [],  # fill in
    "!": [],  # fill in
    "negthinspace": [],  # fill in
    "negmedspace": [],  # fill in
    "negthickspace": [],  # fill in

    # 5. Logic and Set Theory
    "forall": ['∀'],
    "complement": ['∁'],
    "therefore": ['∴'],
    "emptyset": ['∅'],
    "exists": ['∃'],
    "subset": ['⊂'],
    "because": ['∵'],
    "empty": ['∅'],
    "exist": ['∃'],
    "supset": ['⊃'],
    "mapsto": ['↦'],
    "varnothing": ['∅'],
    "nexists": ['∄'],
    "mid": ['∣'],
    "to": ['→'],
    "implies": ['⟹', ' '],
    "in": ['∈'],
    "land": ['∧'],
    "gets": ['←'],
    "impliedby": ['⟸', ' '],
    "isin": ['∈'],
    "lor": ['∨'],
    "leftrightarrow": ['↔'],
    "iff": ['⟺', ' '],
    "notin": ['∉'],
    "ni": ['∋'],
    "notni": ['∌'],
    "neg": ['¬'],
    "lnot": ['¬'],

    # 6. Binary Operators
    "cdot": ['⋅'],
    "gtrdot": ['⋗'],
    "cdotp": ['⋅'],
    "intercal": ['⊺'],
    "centerdot": ['⋅'],
    "rhd": ['⊳'],
    "circ": ['∘'],
    "leftthreetimes": ['⋋'],
    "rightthreetimes": ['⋌'],
    "amalg": ['⨿'],
    "circledast": ['⊛'],
    "ldotp": ['.'],
    "rtimes": ['⋊'],
    "And": ['&'],
    "circledcirc": ['⊚'],
    "setminus": ['∖'],
    "ast": ['∗'],
    "circleddash": ['⊝'],
    "lessdot": ['⋖'],
    "smallsetminus": ['∖'],
    "barwedge": ['⊼'],
    "Cup": ['⋓'],
    "lhd": ['⊲'],
    "sqcap": ['⊓'],
    "bigcirc": ['◯'],
    "cup": ['∪'],
    "ltimes": ['⋉'],
    "sqcup": ['⊔'],
    "bmod": ['b', 'm', 'o', 'd'],
    "curlyvee": ['⋎'],
    "mod": ['m', 'o', 'd'],
    "times": ['×'],
    "boxdot": ['⊡'],
    "curlywedge": ['⋏'],
    "mp": ['∓'],
    "unlhd": ['⊴'],
    "boxminus": ['⊟'],
    "div": ['÷'],
    "odot": ['⊙'],
    "unrhd": ['⊵'],
    "boxplus": ['⊞'],
    "divideontimes": ['⋇'],
    "ominus": ['⊖'],
    "uplus": ['⊎'],
    "boxtimes": ['⊠'],
    "dotplus": ['∔'],
    "oplus": ['⊕'],
    "vee": ['∨'],
    "bullet": ['∙'],
    "doublebarwedge": ['⩞'],
    "otimes": ['⊗'],
    "veebar": ['⊻'],
    "Cap": ['⋒'],
    "doublecap": ['⋒'],
    "oslash": ['⊘'],
    "wedge": ['∧'],
    "cap": ['∩'],
    "doublecup": ['⋓'],
    "pm": ['±'],
    "plusmn": ['±'],
    "wr": ['≀'],

    # 7. Math Operators
    "arcsin": ['a', 'r', 'c', 's', 'i', 'n'],
    "cosec": ['c', 'o', 's', 'e', 'c'],
    "deg": ['d', 'e', 'g'],
    "sec": ['s', 'e', 'c'],
    "arccos": ['a', 'r', 'c', 'c', 'o', 's'],
    "cosh": ['c', 'o', 's', 'h'],
    "dim": ['d', 'i', 'm'],
    "sin": ['s', 'i', 'n'],
    "arctan": ['a', 'r', 'c', 't', 'a', 'n'],
    "cot": ['c', 'o', 't'],
    "exp": ['e', 'x', 'p'],
    "sinh": ['s', 'i', 'n', 'h'],
    "arctg": ['a', 'r', 'c', 't', 'g'],
    "cotg": ['c', 'o', 't', 'g'],
    "hom": ['h', 'o', 'm'],
    "sh": ['s', 'h'],
    "arcctg": ['a', 'r', 'c', 'c', 't', 'g'],
    "coth": ['c', 'o', 't', 'h'],
    "ker": ['k', 'e', 'r'],
    "tan": ['t', 'a', 'n'],
    "arg": ['a', 'r', 'g'],
    "csc": ['c', 's', 'c'],
    "lg": ['l', 'g'],
    "tanh": ['t', 'a', 'n', 'h'],
    "ch": ['c', 'h'],
    "ctg": ['c', 't', 'g'],
    "ln": ['l', 'n'],
    "tg": ['t', 'g'],
    "cos": ['c', 'o', 's'],
    "cth": ['c', 't', 'h'],
    "log": ['l', 'o', 'g'],
    "th": ['t', 'h'],
    "argmax": ['a', 'r', 'g', 'm', 'a', 'x'],
    "injlim": ['i', 'n', 'j', 'l', 'i', 'm'],
    "min": ['m', 'i', 'n'],
    # "varinjlim": ['l', 'i', 'm'],
    "argmin": ['a', 'r', 'g', 'm', 'i', 'n'],
    "lim": ['l', 'i', 'm'],
    "plim": ['p', 'l', 'i', 'm'],
    # "varliminf": ['l', 'i', 'm'],
    "det": ['d', 'e', 't'],
    "liminf": ['l', 'i', 'm', 'i', 'n', 'f'],
    "Pr": ['P', 'r'],
    # "varlimsup": ['l', 'i', 'm'],
    "gcd": ['g', 'c', 'd'],
    "limsup": ['l', 'i', 'm', 's', 'u', 'p'],
    "projlim": ['p', 'r', 'o', 'j', 'l', 'i', 'm'],
    # "varprojlim": ['l', 'i', 'm'],
    "inf": ['i', 'n', 'f'],
    "max": ['m', 'a', 'x'],
    "sup": ['s', 'u', 'p'],

    # 8. Relations
    "doteqdot": ['≑'],
    "lessapprox": ['⪅'],
    "smile": ['⌣'],
    "eqcirc": ['≖'],
    "lesseqgtr": ['⋚'],
    "sqsubset": ['⊏'],
    "eqcolon": ['∹'],
    "minuscolon": ['∹'],
    "lesseqqgtr": ['⪋'],
    "sqsubseteq": ['⊑'],
    "Eqcolon": ['‒', '∶', '∶'],
    "minuscoloncolon": ['‒', '∶', '∶'],
    "lessgtr": ['≶'],
    "sqsupset": ['⊐'],
    "approx": ['≈'],
    "eqqcolon": ['≕'],
    "equalscolon": ['≕'],
    "lesssim": ['≲'],
    "sqsupseteq": ['⊒'],
    "approxcolon": ['≈', '∶'],
    "Eqqcolon": ['=', '∷'],
    "equalscoloncolon": ['=', '∷'],
    "ll": ['≪'],
    "Subset": ['⋐'],
    "approxcoloncolon": ['≈', '∷'],
    "eqsim": ['≂'],
    "lll": ['⋘'],
    "sub": ['⊂'],
    "approxeq": ['≊'],
    "eqslantgtr": ['⪖'],
    "llless": ['⋘'],
    "subseteq": ['⊆'],
    "sube": ['⊆'],
    "asymp": ['≍'],
    "eqslantless": ['⪕'],
    "subseteqq": ['⫅'],
    "backepsilon": ['∍'],
    "equiv": ['≡'],
    "succ": ['≻'],
    "backsim": ['∽'],
    "fallingdotseq": ['≒'],
    "models": ['⊨'],
    "succapprox": ['⪸'],
    "backsimeq": ['⋍'],
    "frown": ['⌢'],
    "multimap": ['⊸'],
    "succcurlyeq": ['≽'],
    "between": ['≬'],
    "ge": ['≥'],
    "origof": ['⊶'],
    "succeq": ['⪰'],
    "bowtie": ['⋈'],
    "geq": ['≥'],
    "owns": ['∋'],
    "succsim": ['≿'],
    "bumpeq": ['≏'],
    "geqq": ['≧'],
    "parallel": ['∥'],
    "Supset": ['⋑'],
    "Bumpeq": ['≎'],
    "geqslant": ['⩾'],
    "perp": ['⊥'],
    "circeq": ['≗'],
    "gg": ['≫'],
    "pitchfork": ['⋔'],
    "supseteq": ['⊇'],
    "supe": ['⊇'],
    "colonapprox": ['∶', '≈'],
    "ggg": ['⋙'],
    "prec": ['≺'],
    "supseteqq": ['⫆'],
    "Colonapprox": ['∷', '≈'],
    "coloncolonapprox": ['∷', '≈'],
    "gggtr": ['⋙'],
    "precapprox": ['⪷'],
    "thickapprox": ['≈'],
    "coloneq": ['∶', '‒'],
    "colonminus": ['∶', '‒'],
    "preccurlyeq": ['≼'],
    "thicksim": ['∼'],
    "Coloneq": ['∷', '='],
    "coloncolonminus": ['∷', '='],
    "gtrapprox": ['⪆'],
    "preceq": ['⪯'],
    "trianglelefteq": ['⊴'],
    "coloneqq": ['≔'],
    "colonequals": ['≔'],
    "gtreqless": ['⋛'],
    "precsim": ['≾'],
    "triangleq": ['≜'],
    "Coloneqq": ['⩴', ' '],
    "coloncolonequals": ['⩴', ' '],
    "gtreqqless": ['⪌'],
    "propto": ['∝'],
    "trianglerighteq": ['⊵'],
    "colonsim": ['∶', '∼'],
    "gtrless": ['≷'],
    "risingdotseq": ['≓'],
    "varpropto": ['∝'],
    "Colonsim": ['∷', '∼'],
    "coloncolonsim": ['∷', '∼'],
    "gtrsim": ['≳'],
    "shortmid": ['∣'],
    "vartriangle": ['△'],
    "cong": ['≅'],
    "imageof": ['⊷'],
    "shortparallel": ['∥'],
    "vartriangleleft": ['⊲'],
    "curlyeqprec": ['⋞'],
    "sim": ['∼'],
    "vartriangleright": ['⊳'],
    "curlyeqsucc": ['⋟'],
    "Join": ['⋈'],
    "simcolon": ['∼', '∶'],
    "vcentcolon": ['∶'],
    "ratio": ['∶'],
    "dashv": ['⊣'],
    "le": ['≤'],
    "simcoloncolon": ['∼', '∷'],
    "vdash": ['⊢'],
    "dblcolon": ['∷'],
    "coloncolon": ['∷'],
    "leq": ['≤'],
    "simeq": ['≃'],
    "vDash": ['⊨'],
    "doteq": ['≐'],
    "leqq": ['≦'],
    "smallfrown": ['⌢'],
    "Vdash": ['⊩'],
    "Doteq": ['≑'],
    "leqslant": ['⩽'],
    "smallsmile": ['⌣'],
    "Vvdash": ['⊪'],

    # 9. Negated Relations
    "gnapprox": ['⪊'],
    "ngeqslant": ['≱'],
    "nsubseteq": ['⊈'],
    "precneqq": ['⪵'],
    "gneq": ['⪈'],
    "ngtr": ['≯'],
    "nsubseteqq": ['⊈'],
    "precnsim": ['⋨'],
    "gneqq": ['≩'],
    "nleq": ['≰'],
    "nsucc": ['⊁'],
    "subsetneq": ['⊊'],
    "gnsim": ['⋧'],
    "nleqq": ['≰'],
    "nsucceq": ['⋡'],
    "subsetneqq": ['⫋'],
    "gvertneqq": ['≩'],
    "nleqslant": ['≰'],
    "nsupseteq": ['⊉'],
    "succnapprox": ['⪺'],
    "lnapprox": ['⪉'],
    "nless": ['≮'],
    "nsupseteqq": ['⊉'],
    "succneqq": ['⪶'],
    "lneq": ['⪇'],
    "nmid": ['∤'],
    "ntriangleleft": ['⋪'],
    "succnsim": ['⋩'],
    "lneqq": ['≨'],
    "ntrianglelefteq": ['⋬'],
    "supsetneq": ['⊋'],
    "lnsim": ['⋦'],
    "ntriangleright": ['⋫'],
    "supsetneqq": ['⫌'],
    "lvertneqq": ['≨'],
    "nparallel": ['∦'],
    "ntrianglerighteq": ['⋭'],
    "varsubsetneq": ['⊊'],
    "ncong": ['≆'],
    "nprec": ['⊀'],
    "nvdash": ['⊬'],
    "varsubsetneqq": ['⫋'],
    "ne": ['≠'],
    "npreceq": ['⋠'],
    "nvDash": ['⊭'],
    "varsupsetneq": ['⊋'],
    "neq": ['≠'],
    "nshortmid": ['∤'],
    "nVDash": ['⊯'],
    "varsupsetneqq": ['⫌'],
    "ngeq": ['≱'],
    "nshortparallel": ['∦'],
    "nVdash": ['⊮'],
    "ngeqq": ['≱'],
    "nsim": ['≁'],
    "precnapprox": ['⪹'],

    # 10. Arrows
    "circlearrowleft": ['↺'],
    "leftharpoonup": ['↼'],
    "rArr": ['⇒'],
    "circlearrowright": ['↻'],
    "leftleftarrows": ['⇇'],
    "rarr": ['→'],
    "curvearrowleft": ['↶'],
    "restriction": ['↾'],
    "curvearrowright": ['↷'],
    "Leftrightarrow": ['⇔'],
    "rightarrow": ['→'],
    "Darr": ['⇓'],
    "leftrightarrows": ['⇆'],
    "Rightarrow": ['⇒'],
    "dArr": ['⇓'],
    "leftrightharpoons": ['⇋'],
    "rightarrowtail": ['↣'],
    "darr": ['↓'],
    "leftrightsquigarrow": ['↭'],
    "rightharpoondown": ['⇁'],
    "dashleftarrow": ['⇠'],
    "Lleftarrow": ['⇚'],
    "rightharpoonup": ['⇀'],
    "dashrightarrow": ['⇢'],
    "longleftarrow": ['⟵', ' '],
    "rightleftarrows": ['⇄'],
    "Longleftarrow": ['⟸', ' '],
    "rightleftharpoons": ['⇌'],
    "longleftrightarrow": ['⟷', ' '],
    "rightrightarrows": ['⇉'],
    "downdownarrows": ['⇊'],
    "Longleftrightarrow": ['⟺', ' '],
    "rightsquigarrow": ['⇝'],
    "downharpoonleft": ['⇃'],
    "longmapsto": ['⟼', ' '],
    "Rrightarrow": ['⇛'],
    "downharpoonright": ['⇂'],
    "longrightarrow": ['⟶', ' '],
    "Rsh": ['↱'],
    "Longrightarrow": ['⟹', ' '],
    "searrow": ['↘'],
    "Harr": ['⇔'],
    "looparrowleft": ['↫'],
    "swarrow": ['↙'],
    "hArr": ['⇔'],
    "looparrowright": ['↬'],
    "harr": ['↔'],
    "Lrarr": ['⇔'],
    "twoheadleftarrow": ['↞'],
    "hookleftarrow": ['↩'],
    "lrArr": ['⇔'],
    "twoheadrightarrow": ['↠'],
    "hookrightarrow": ['↪'],
    "lrarr": ['↔'],
    "Uarr": ['⇑'],
    "Lsh": ['↰'],
    "uArr": ['⇑'],
    "uarr": ['↑'],
    "nearrow": ['↗'],
    "Larr": ['⇐'],
    "nleftarrow": ['↚'],
    "lArr": ['⇐'],
    "nLeftarrow": ['⇍'],
    "larr": ['←'],
    "nleftrightarrow": ['↮'],
    "leadsto": ['⇝'],
    "nLeftrightarrow": ['⇎'],
    "upharpoonleft": ['↿'],
    "leftarrow": ['←'],
    "nrightarrow": ['↛'],
    "upharpoonright": ['↾'],
    "Leftarrow": ['⇐'],
    "nRightarrow": ['⇏'],
    "upuparrows": ['⇈'],
    "leftarrowtail": ['↢'],
    "nwarrow": ['↖'],
    "leftharpoondown": ['↽'],
    "Rarr": ['⇒'],

    # 11. Symbols and Punctuation
    "dots": ['…'],
    "TeXicode": ['T', 'ₑ', 'X', 'ᵢ', 'c', 'ₒ', 'd', 'ₑ'],
    "%": ['%'],
    "cdots": ['⋯'],
    "LaTeX": ['L', 'ᴬ', 'T', 'ₑ', 'X'],
    "#": ['#'],
    "ddots": ['⋱'],
    "TeX": ['T', 'ₑ', 'X'],
    "&": ['&'],
    "ldots": ['…'],
    "_": ['_'],
    "vdots": ['⋮'],
    "infty": ['∞'],
    "textunderscore": ['_'],  # \text-wrapped
    "dotsb": ['⋯'],
    "infin": ['∞'],
    "--": ['⸺', ' '],  # \text-wrapped
    "dotsc": ['…'],
    "checkmark": ['✓'],
    "textendash": ['–'],  # \text-wrapped
    "dotsi": ['⋯'],
    "dag": ['†'],
    "---": ['⸻', '⸻', ' '],  # \text-wrapped
    "dotsm": ['⋯'],
    "dagger": ['†'],
    "textemdash": ['—'],  # \text-wrapped
    "dotso": ['…'],
    "textdagger": ['†'],  # \text-wrapped
    "textasciitilde": ['~'],  # \text-wrapped
    "sdot": ['⋅'],
    "ddag": ['‡'],
    "textasciicircum": ['^'],  # \text-wrapped
    "mathellipsis": ['…'],
    "ddagger": ['‡'],
    "textellipsis": ['…'],  # \text-wrapped
    "textdaggerdbl": ['‡'],  # \text-wrapped
    "textquoteleft": ['‘'],  # \text-wrapped
    "Box": ['□'],
    "Dagger": ['‡'],
    "lq": ['‘'],
    "square": ['□'],
    "angle": ['∠'],
    "textquoteright": ['’'],  # \text-wrapped
    "blacksquare": ['■'],
    "measuredangle": ['∡'],
    "rq": ['′'],
    "triangle": ['△'],
    "sphericalangle": ['∢'],
    "textquotedblleft": ['“'],  # \text-wrapped
    "triangledown": ['▽'],
    "top": ['⊤'],
    "triangleleft": ['◃'],
    "bot": ['⊥'],
    "textquotedblright": ['”'],  # \text-wrapped
    "triangleright": ['▹'],
    "$": ['$'],
    "colon": [':'],
    "bigtriangledown": ['▽'],
    "textdollar": ['$'],  # \text-wrapped
    "backprime": ['‵'],
    "bigtriangleup": ['△'],
    "pounds": ['£'],
    "prime": ['′'],
    "blacktriangle": ['▲'],
    "mathsterling": ['£'],
    "textless": ['<'],  # \text-wrapped
    "blacktriangledown": ['▼'],
    "textsterling": ['£'],  # \text-wrapped
    "textgreater": ['>'],  # \text-wrapped
    "blacktriangleleft": ['◀'],
    "yen": ['¥'],
    "textbar": ['|'],  # \text-wrapped
    "blacktriangleright": ['▶'],
    "surd": ['√'],
    "textbardbl": ['‖'],  # \text-wrapped
    "diamond": ['⋄'],
    "degree": ['°'],
    "textbraceleft": ['{'],  # \text-wrapped
    "Diamond": ['◊'],
    "textdegree": ['°'],  # \text-wrapped
    "textbraceright": ['}'],  # \text-wrapped
    "lozenge": ['◊'],
    "mho": ['℧'],
    "textbackslash": ['\\'],  # \text-wrapped
    "blacklozenge": ['⧫'],
    "diagdown": ['╲'],
    "P": ['¶'],  # \text-wrapped
    "star": ['⋆'],
    "diagup": ['╱'],
    "S": ['§'],  # \text-wrapped
    "bigstar": ['★'],
    "flat": ['♭'],
    "sect": ['§'],  # \text-wrapped
    "clubsuit": ['♣'],
    "natural": ['♮'],
    "copyright": ['©'],
    "clubs": ['♣'],
    "sharp": ['♯'],
    "circledR": ['®'],
    "diamondsuit": ['♢'],
    "heartsuit": ['♡'],
    "textregistered": ['Ⓡ'],  # \text-wrapped
    "diamonds": ['♢'],
    "hearts": ['♡'],
    "circledS": ['Ⓢ'],
    "spadesuit": ['♠'],
    "spades": ['♠'],
    "maltese": ['✠'],
    "minuso": ['⦵'],

}
